car = 'subaru'
print("Is car == 'subaru' ? I predict True.")
print(car == 'subaru')
print("\n Is car == 'audi' ? I predict False")
print(car == 'audi')
print(1 == 2)
print('a' == 'b')
print('a' != 'a')
print("Tony" == "James")
print(3 - 5 == 8)
print(1 != 2)
print('a' != 'b')
print('a' == 'a')
print("Tony" != "James")
print(3 - 5 != 8)
