print("James" == "JAMES")
print("james" == "James".lower())
print(1 > 2)
print(1 >= 2)
print(1 < 2)
print(1 <= 2)
print(2 > 1 and 2 < 3)
print(2 > 5 or 2 < 3)
print(3 > 8 or 3 < 1)
family = ['Tony', 'James', 'Jessica']
print('Tony' in family)
print('Leo' in family)
